### ISSUE TITLE
Theory of constraints

### ISSUE THREAD

**Issue by tomhoyland** [agileengineeringpodcast/podcast-topics#13]
Applying theory of constraints across teams, enterprises and industries. Can we do more?

How can we use constraints to drive innovation, encourage communication and promote neurodiversity?

**Comment by lgulliver** [comment]
Hey @tomhoyland, thanks for you submission!

**Comment by tomhoyland** [comment]
Talking points 
- bottlenecks 
- policies 
- innovation 
- collaboration
- tech
- language
- decay and volatility 
- monitoring
