### ISSUE TITLE
Convincing old-world developers that Agile is not hell

### ISSUE THREAD

**Issue by Vitani** [agileengineeringpodcast/podcast-topics#2]
Many old-world developers have the wrong understanding of Agile, what it is, how it can help, where it can make positive changes, and how it can speed up development. This is (most likely - investigation needed) due to bad previous experiences of Agile being rolled out in their department, and/or poor Scrum Masters.

Agile, done right, is not hell. But it's not a silver bullet either. It takes hard work, and team participation to bring fourth the benefits.

**Comment by lgulliver** [comment]
Discussed in our first episode which you can now find here: https://open.spotify.com/episode/4ZLpE7H3pZlPrJAZolM2SH?si=rU-H3DqoR9KL_FtXycXT-g
