### ISSUE TITLE
Self-taught vs degree-educated, who makes the better developer?

### ISSUE THREAD

**Issue by Vitani** [agileengineeringpodcast/podcast-topics#9]
Lots of developers who are self-taught don't know the ins & outs of how a computer work, and what makes a good algorithm. Conversely CS students are fed answers and don't always know how to problem solve on their own. For a new developer starting out on their journey, which path is going to lead them to more job opportunities? And which type would you prefer to hire?

**Comment by lgulliver** [comment]
@Vitani after further review, we're going to have to reject this suggestion. While a good topic to discuss, it doesn't really fit in with Agile Engineering's remit.
